-- Roles. CREATE ROLE is transactional, so it may stay inside a DO block.
DO $$
BEGIN
   IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'inventoryuser') THEN
      CREATE ROLE inventoryuser WITH LOGIN PASSWORD 'dev123';
   END IF;
END
$$;

DO $$
BEGIN
   IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'orderuser') THEN
      CREATE ROLE orderuser WITH LOGIN PASSWORD 'dev123';
   END IF;
END
$$;

-- Databases. CREATE DATABASE cannot run inside a transaction, and every DO block runs in one,
-- so it cannot be wrapped in "IF NOT EXISTS" either (PostgreSQL has no such form). The
-- statement is generated by a query and executed with psql's \gexec instead, which keeps the
-- script idempotent without the forbidden transaction.
SELECT 'CREATE DATABASE inventorydb WITH OWNER = inventoryuser'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'inventorydb')\gexec

SELECT 'CREATE DATABASE orderdb WITH OWNER = orderuser'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'orderdb')\gexec

-- Schemas. A schema belongs to one database, so it has to be created in that database and not
-- in the one this script happens to be running in: the file is mounted into both the inventory
-- and the order PostgreSQL containers. order-service sets hibernate.default_schema=orders and
-- fails to create its tables while the schema is missing.
\connect inventorydb
CREATE SCHEMA IF NOT EXISTS inventory;

\connect orderdb
CREATE SCHEMA IF NOT EXISTS orders;
