spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;NON_KEYWORDS=ORDERS,ORDER,USER
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        default_schema: public
        dialect: org.hibernate.dialect.H2Dialect
  kafka:
    enabled: false
logging:
  level:
    com.orderplatform.order: INFO
    org.springframework.security: WARN
