spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/orderplatform
    username: platform
    password: dev123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    enabled: false  # Отключено по умолчанию, включается через profiles (docker/dev)
    consumer:
      group-id: user-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

    producer:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
server:
  port: 8082

logging:
  level:
    com.orderplatform.user: DEBUG