spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/userdb
    username: userplatform
    password: dev123
  sql:
    init:
      mode: always
      continue-on-error: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: user_profile
  kafka:
    enabled: true
    bootstrap-servers: localhost:19092  # Внешний порт Redpanda

server:
  port: 8082

logging:
  level:
    com.orderplatform.user: DEBUG
    org.springframework.kafka: DEBUG
