spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/orderplatform
    username: platform
    password: dev123

  jpa:
    properties:
      hibernate:
        default_schema: user_profile

  kafka:
    bootstrap-servers: redpanda:9092
    consumer:
      group-id: user-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.orderplatform.user.dto,com.orderplatform.auth.dto"

server:
  port: 8082

logging:
  level:
    com.orderplatform.user: INFO
    org.springframework.kafka: INFO
