spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/orderplatform
    username: platform
    password: dev123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    enabled: true
    bootstrap-servers: localhost:19092  # Внешний порт Redpanda

server:
  port: 8082

logging:
  level:
    com.orderplatform.user: DEBUG