spring:
  datasource:
    url: jdbc:postgresql://user-db:5432/userdb
    username: userplatform
    password: dev123
  sql:
    init:
      mode: always
      continue-on-error: true
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        default_schema: user_profile
  kafka:
    enabled: true
    bootstrap-servers: redpanda:9092
    consumer:
      group-id: user-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.orderplatform.user.dto,com.orderplatform.auth.dto"

server:
  port: 8082

logging:
  level:
    com.orderplatform.user: INFO
    org.springframework.kafka: DEBUG
