de:
  flapdoodle:
    mongodb:
      embedded:
        version: 7.0.4

spring:
  kafka:
    enabled: false
  security:
    enabled: false
  data:
    mongodb:
      host: localhost
      port: 0
      database: notificationdb
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
logging:
  level:
    com.orderplatform.notification: INFO
