spring:
  cloud:
    gateway:
      server:
        webflux:
          default-filters: []
          routes: []
  data:
    redis:
      host: localhost
      port: 6379
logging:
  level:
    com.orderplatform.gateway: INFO
